version: "3"
services:
  blog:
    build: .
    container_name: blog
    hostname: blog
    restart: always
    ports:
      - 80:80
    volumes:
      - ./prototype/:/html

  # blog:
  #   image: httpd
  #   container_name: blog
  #   hostname: blog
  #   restart: always
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./prototype/:/var/www/html